server:
  port: 8096
spring:
  cloud:
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8197
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: feign-sentinel-01

# fallback
feign:
  sentinel:
    enabled: true

