spring:
  application:
    name: spring-cloud-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 182.61.11.6:8848

    sentinel:
      transport:
        port: 8698
        dashboard: 127.0.0.1:8698
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: NACOS-CONSUMER
          # 采用 LoadBalanceClient 方式请求，以 lb:// 开头，后面的是注册在 Nacos 上的服务名
          uri: lb://nacos-discovery-consumer
          # Predicate 翻译过来是“谓词”的意思，必须，主要作用是匹配用户的请求，有很多种用法
          predicates:
            # Method 方法谓词，这里是匹配 GET 和 POST 请求
            - Method=GET,POST
        - id: NACOS-CONSUMER-FEIGN
          uri: lb://nacos-sentinel-feign
          predicates:
            - Method=GET,POST
server:
  port: 8088